Add 'while importing X at Y' error chains.
So that you can see where exactly things go wrong during an import
chain. This is especially useful when something complicated goes wrong
inside of an import.

For instance:
ERROR: must import type, but importing value: test.import_identifier@1.0::types:Foo
while importing test.import_identifier@1.0::types:Foo at system/tools/hidl/test/error_test/import_identifier/1.0/IFoo.hal:19.8-44.

Bug: N/A
Test: manual
Change-Id: Ifd1baa7a7405e74c2ba6c4b65944110a77069bda